/** 常用 HTML 实体速查表（纯数据）。字符本身在运行时从完整实体表查出，避免手写出错 */

import { NAMED_ENTITIES } from './html-entities'

export type EntityCategory =
  'common' | 'space' | 'punct' | 'currency' | 'math' | 'arrow' | 'greek' | 'symbol' | 'latin'

export const ENTITY_CATEGORIES: { id: EntityCategory; label: string }[] = [
  { id: 'common', label: '常用' },
  { id: 'space', label: '空白与不可见' },
  { id: 'punct', label: '标点' },
  { id: 'currency', label: '货币' },
  { id: 'math', label: '数学' },
  { id: 'arrow', label: '箭头' },
  { id: 'greek', label: '希腊字母' },
  { id: 'symbol', label: '符号' },
  { id: 'latin', label: '拉丁字母' },
]

/** [名称, 中文说明] */
const RAW: Record<EntityCategory, [string, string][]> = {
  common: [
    ['amp', '和号'],
    ['lt', '小于号'],
    ['gt', '大于号'],
    ['quot', '双引号'],
    ['apos', '单引号'],
    ['nbsp', '不换行空格'],
    ['copy', '版权'],
    ['reg', '注册商标'],
    ['trade', '商标'],
    ['hellip', '省略号'],
    ['mdash', '破折号（长）'],
    ['ndash', '连接号（短）'],
    ['laquo', '左书名号 «'],
    ['raquo', '右书名号 »'],
    ['ldquo', '左双引号'],
    ['rdquo', '右双引号'],
    ['lsquo', '左单引号'],
    ['rsquo', '右单引号'],
    ['middot', '间隔点'],
    ['bull', '项目符号'],
    ['deg', '度'],
    ['plusmn', '正负号'],
    ['times', '乘号'],
    ['divide', '除号'],
    ['yen', '人民币 / 日元'],
    ['euro', '欧元'],
    ['check', '对勾'],
    ['rarr', '右箭头'],
  ],
  space: [
    ['nbsp', '不换行空格 U+00A0'],
    ['ensp', '半角空格（en）'],
    ['emsp', '全角空格（em）'],
    ['emsp13', '1/3 em 空格'],
    ['emsp14', '1/4 em 空格'],
    ['numsp', '数字宽度空格'],
    ['puncsp', '标点宽度空格'],
    ['thinsp', '窄空格'],
    ['hairsp', '极窄空格'],
    ['ZeroWidthSpace', '零宽空格'],
    ['zwnj', '零宽不连字'],
    ['zwj', '零宽连字'],
    ['lrm', '从左到右标记'],
    ['rlm', '从右到左标记'],
    ['shy', '软连字符'],
    ['NoBreak', '词连接符'],
    ['NewLine', '换行符'],
    ['Tab', '制表符'],
  ],
  punct: [
    ['iexcl', '倒感叹号'],
    ['iquest', '倒问号'],
    ['sect', '章节号'],
    ['para', '段落号'],
    ['dagger', '剑号'],
    ['Dagger', '双剑号'],
    ['permil', '千分号'],
    ['prime', '角分 / 英尺'],
    ['Prime', '角秒 / 英寸'],
    ['lsaquo', '单左尖引号'],
    ['rsaquo', '单右尖引号'],
    ['sbquo', '单低引号'],
    ['bdquo', '双低引号'],
    ['oline', '上划线'],
    ['brvbar', '断竖线'],
    ['horbar', '引文破折号'],
    ['nldr', '两点省略号'],
    ['uml', '分音符'],
    ['acute', '尖音符'],
    ['cedil', '软音符'],
    ['circ', '抑扬符'],
    ['tilde', '波浪符'],
    ['macr', '长音符'],
  ],
  currency: [
    ['dollar', '美元'],
    ['cent', '分'],
    ['pound', '英镑'],
    ['yen', '人民币 / 日元'],
    ['euro', '欧元'],
    ['curren', '通用货币符号'],
    ['fnof', '弗罗林 / 函数'],
  ],
  math: [
    ['plusmn', '正负号'],
    ['times', '乘号'],
    ['divide', '除号'],
    ['minus', '减号'],
    ['ne', '不等于'],
    ['le', '小于等于'],
    ['ge', '大于等于'],
    ['asymp', '约等于'],
    ['equiv', '恒等于'],
    ['cong', '全等'],
    ['sim', '相似'],
    ['prop', '正比于'],
    ['infin', '无穷大'],
    ['sum', '求和'],
    ['prod', '连乘'],
    ['radic', '根号'],
    ['int', '积分'],
    ['part', '偏微分'],
    ['nabla', '梯度'],
    ['forall', '任意'],
    ['exist', '存在'],
    ['empty', '空集'],
    ['isin', '属于'],
    ['notin', '不属于'],
    ['sub', '子集'],
    ['sup', '超集'],
    ['sube', '子集或等于'],
    ['supe', '超集或等于'],
    ['cap', '交集'],
    ['cup', '并集'],
    ['and', '逻辑与'],
    ['or', '逻辑或'],
    ['not', '逻辑非'],
    ['there4', '所以'],
    ['becaus', '因为'],
    ['ang', '角'],
    ['perp', '垂直'],
    ['sdot', '点乘'],
    ['oplus', '直和'],
    ['otimes', '张量积'],
    ['frac12', '二分之一'],
    ['frac14', '四分之一'],
    ['frac34', '四分之三'],
    ['frac13', '三分之一'],
    ['sup2', '平方'],
    ['sup3', '立方'],
    ['micro', '微'],
    ['lceil', '左上取整'],
    ['rceil', '右上取整'],
    ['lfloor', '左下取整'],
    ['rfloor', '右下取整'],
  ],
  arrow: [
    ['larr', '左箭头'],
    ['uarr', '上箭头'],
    ['rarr', '右箭头'],
    ['darr', '下箭头'],
    ['harr', '左右箭头'],
    ['varr', '上下箭头'],
    ['nwarr', '左上箭头'],
    ['nearr', '右上箭头'],
    ['searr', '右下箭头'],
    ['swarr', '左下箭头'],
    ['lArr', '左双箭头'],
    ['uArr', '上双箭头'],
    ['rArr', '右双箭头（推出）'],
    ['dArr', '下双箭头'],
    ['hArr', '左右双箭头（等价）'],
    ['crarr', '回车'],
    ['map', '映射'],
    ['larrhk', '左钩箭头'],
    ['rarrhk', '右钩箭头'],
    ['olarr', '逆时针'],
    ['orarr', '顺时针'],
    ['lrarr', '左右换向'],
    ['rarrw', '波浪右箭头'],
  ],
  greek: [
    ['Alpha', '阿尔法'],
    ['Beta', '贝塔'],
    ['Gamma', '伽马'],
    ['Delta', '德尔塔'],
    ['Theta', '西塔'],
    ['Lambda', '兰姆达'],
    ['Pi', '派'],
    ['Sigma', '西格玛'],
    ['Phi', '斐'],
    ['Psi', '普西'],
    ['Omega', '欧米伽'],
    ['alpha', '阿尔法'],
    ['beta', '贝塔'],
    ['gamma', '伽马'],
    ['delta', '德尔塔'],
    ['epsilon', '艾普西隆'],
    ['zeta', '泽塔'],
    ['eta', '伊塔'],
    ['theta', '西塔'],
    ['iota', '约塔'],
    ['kappa', '卡帕'],
    ['lambda', '兰姆达'],
    ['mu', '缪'],
    ['nu', '纽'],
    ['xi', '克西'],
    ['omicron', '奥米克戎'],
    ['pi', '派'],
    ['rho', '柔'],
    ['sigma', '西格玛'],
    ['sigmaf', '词尾西格玛'],
    ['tau', '陶'],
    ['upsilon', '宇普西隆'],
    ['phi', '斐'],
    ['chi', '希'],
    ['psi', '普西'],
    ['omega', '欧米伽'],
  ],
  symbol: [
    ['check', '对勾'],
    ['cross', '叉号'],
    ['star', '空心星'],
    ['starf', '实心星'],
    ['hearts', '红心'],
    ['diams', '方块'],
    ['clubs', '梅花'],
    ['spades', '黑桃'],
    ['loz', '菱形'],
    ['phone', '电话'],
    ['female', '女性'],
    ['male', '男性'],
    ['sung', '音符'],
    ['flat', '降号'],
    ['natural', '还原号'],
    ['sharp', '升号'],
    ['copysr', '录音版权'],
    ['trade', '商标'],
    ['reg', '注册商标'],
    ['copy', '版权'],
    ['ohm', '欧姆'],
    ['angst', '埃'],
    ['incare', '转交'],
    ['numero', '编号'],
    ['malt', '马耳他十字'],
    ['sext', '六角星'],
    ['squ', '空心方块'],
    ['squf', '实心方块'],
    ['cir', '空心圆'],
    ['bigtriangleup', '空心上三角'],
    ['blacktriangle', '实心小上三角'],
    ['ordf', '阴性序数'],
    ['ordm', '阳性序数'],
  ],
  latin: [
    ['Agrave', 'A 抑音符'],
    ['Aacute', 'A 尖音符'],
    ['Auml', 'A 分音符'],
    ['Aring', 'A 上圆圈'],
    ['AElig', 'AE 连字'],
    ['Ccedil', 'C 软音符'],
    ['Eacute', 'E 尖音符'],
    ['Ntilde', 'N 波浪符'],
    ['Ouml', 'O 分音符'],
    ['Oslash', 'O 斜线'],
    ['Uuml', 'U 分音符'],
    ['szlig', '德语 sharp s'],
    ['agrave', 'a 抑音符'],
    ['aacute', 'a 尖音符'],
    ['acirc', 'a 抑扬符'],
    ['atilde', 'a 波浪符'],
    ['auml', 'a 分音符'],
    ['aring', 'a 上圆圈'],
    ['aelig', 'ae 连字'],
    ['ccedil', 'c 软音符'],
    ['egrave', 'e 抑音符'],
    ['eacute', 'e 尖音符'],
    ['ecirc', 'e 抑扬符'],
    ['euml', 'e 分音符'],
    ['iacute', 'i 尖音符'],
    ['ntilde', 'n 波浪符'],
    ['oacute', 'o 尖音符'],
    ['ouml', 'o 分音符'],
    ['oslash', 'o 斜线'],
    ['uacute', 'u 尖音符'],
    ['uuml', 'u 分音符'],
    ['yuml', 'y 分音符'],
    ['OElig', 'OE 连字'],
    ['oelig', 'oe 连字'],
    ['Scaron', 'S 抑扬符（反）'],
    ['scaron', 's 抑扬符（反）'],
    ['eth', '冰岛语 eth'],
    ['thorn', '冰岛语 thorn'],
  ],
}

export interface EntityRef {
  name: string
  char: string
  codePoint: number
  desc: string
  category: EntityCategory
}

export const ENTITY_REFERENCE: EntityRef[] = ENTITY_CATEGORIES.flatMap(({ id }) =>
  RAW[id].map(([name, desc]) => {
    const char = NAMED_ENTITIES.get(name) ?? ''
    return { name, char, codePoint: char.codePointAt(0) ?? 0, desc, category: id }
  }),
)

/** 按名称、字符、说明、码点（U+2192 / 8594 / 2192）搜索 */
export function searchEntities(
  query: string,
  category: EntityCategory | 'all' = 'all',
): EntityRef[] {
  const q = query.trim().replace(/^&|;$/g, '').toLowerCase()
  const list =
    category === 'all'
      ? // “全部”时去掉重复出现在多个分类里的条目
        ENTITY_REFERENCE.filter((e, i, arr) => arr.findIndex((x) => x.name === e.name) === i)
      : ENTITY_REFERENCE.filter((e) => e.category === category)
  if (!q) return list
  // 码点：U+2192、0x2192、#x2192 或 4 位以上的十六进制；十进制可写作 8594 或 #8594
  const hex = /^(u\+|0x|#x)[0-9a-f]{1,6}$/.test(q)
    ? parseInt(q.replace(/^(u\+|0x|#x)/, ''), 16)
    : /^[0-9a-f]{4,6}$/.test(q)
      ? parseInt(q, 16)
      : NaN
  const dec = /^#?\d+$/.test(q) ? Number(q.replace('#', '')) : NaN
  return list.filter(
    (e) =>
      e.name.toLowerCase().includes(q) ||
      e.char === query.trim() ||
      e.desc.toLowerCase().includes(q) ||
      e.codePoint === dec ||
      e.codePoint === hex,
  )
}
